### ISSUE TITLE
Error when attempting to play a video

### ISSUE THREAD

**Issue by Lucetia** [nixgates/nixgates#3]
Hello,

My roommate just tried to play a video with Seren.  We had to go through several sources before it would actually played.  I tried using the TorrentAPI from PM to play the video, even the one I cached on my own account and it kept saying an error popped up.  Eventually in order to get one to play I had to use the RD Filehoster area of Seren to get it to load.  Below is what I was able to extract from the log where the error occurred.  If any further information is needed please let me know!

This occured on a RPI3 running OSMC with Kodi 17.  I've had a similar problem on Kodi 18 Beta5 on my Xbox One, but haven't figured out how to retrieve the logs from it yet.

https://pastebin.com/eR4DDYXA

_Edit: Added a pastebin link so it wasn't as spammy_

**Comment by nixgates** [comment]
The issue that was faced here was due to the link from the debrid service, it appears that everything from Seren's side was ok but when Kodi tried to retrieve the file from the cloud it failed.

It's highly possible that this was due to issues that have already been fixed on the service providers side so I'm going to close out this issue. 

If you feel that I've closed this incorrectly just let me know.

PS. In future events of issues, could you please use the plugin.video.seren repository. Thank you :)
